### ISSUE TITLE
Select node by it id

### ISSUE THREAD

**Issue by nicdnepr** [patternfly/patternfly-bootstrap-treeview#26] opened 2017-02-15 20:07 UTC
How can I select node by its id without searching by node name? Also I want to autoexplode all parent nodes

**Comment by skateman** [comment] 2017-04-24 14:56
You need to iterate through the nodes returned by `getNodes()` and select it as you would [select from an array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find).

**Comment by skateman** [comment] 2017-07-31 07:13
Seems like duplicate of [this](https://github.com/patternfly/patternfly-bootstrap-treeview/issues/28), closing...

**Closed by skateman** 2017-07-31 07:13 UTC
